"""add_video_processing_metrics

Revision ID: 522b3a7caa46
Revises: 98a1b2abd320
Create Date: 2025-02-03 23:12:25.458570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522b3a7caa46'
down_revision: Union[str, None] = '98a1b2abd320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('processing_duration', sa.Float(), nullable=True))
    op.add_column('videos', sa.Column('transcription_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'transcription_confidence')
    op.drop_column('videos', 'processing_duration')
    # ### end Alembic commands ###
